### ISSUE TITLE
Can i write my app in golang ?

### ISSUE THREAD

**Issue by joeblew99** [waxosuit/wascap-codec#2]
It looks like its just protobufs and so maybe i could in theory write in golang using the protobuf to do messaging, security calls etc.
But when cross compiled to WASM, will waxosuit be able to run it.

For compilation of golang to WASM i am using https://github.com/tinygo-org/tinygo
You get smaller binaries.

**Comment by autodidaddict** [comment]
Yes, you'll be able to write your application in `Go`. Today, we've got the [wascap-guest](https://github.com/waxosuit/wascap-guest) Rust SDK that wraps the [wascap](https://wascap.io) interface for you and makes using capabilities easier. I have plans to work on a `Go` version of this SDK but I haven't had a chance to start exploring it yet.

The short answer is - _any_ language capable of producing a WebAssembly module can run as a guest module within Waxosuit. For now, we have a Rust SDK that makes this easy and automatic. The next SDK we can plan on building is `Go`.

**Comment by autodidaddict** [comment]
There is active research happening on how Go support might be possible, including using TinyGo. Right now the Go WebAssembly ecosystem has some pretty big weak points and is shallow in some areas. I will definitely post blogs and/or documentation as soon as we've got anything available for Go (and if not, explanations as to why)
